### ISSUE TITLE
Chrome Canary 54.x

### ISSUE THREAD

**Issue by rahilwazir** [wspl/mactype-hack#10]
The [chromium](https://github.com/wspl/mactype-hack/blob/master/chromium.md) solution is out of date for the latest Chrome canary 54.x atleast
- No option to disable direct-write
- No option of Step2 -> step2 `#enable-one-copy`

Either way it didn't work, [read more](https://productforums.google.com/d/msg/chrome/Q6QGBRvULbQ/lfe3Ot2ECAAJ)

**Comment by wspl** [comment]
Yes, it is a bad news for chrome users who is using Mactype.
Up to now, there is no way to disable `direct-write` option on the latest Chrome release version.
So if chrome continues to be so stubborn, I will use the Firefox browser.

**Comment by wspl** [comment]
A new way to enhance the font rendering effect on Chrome/Firefox with direct-write is out: [https://github.com/wspl/mactype-hack/blob/master/direct-write.md](https://github.com/wspl/mactype-hack/blob/master/direct-write.md)

**Comment by gongenzaka** [comment]
How do I fix it? just replaced mactype files but chrome still looks the same

**Comment by rahilwazir** [comment]
@gongenzaka Did you follow the steps from [here](https://github.com/wspl/mactype-hack/blob/master/direct-write.md)?

**Comment by armak** [comment]
I did and it doesn't change anything in Chrome 52/53/54. Font rendering stays the same DirectWrite mess in two different Windows 7 configurations. Any ideas?
