### ISSUE TITLE
Firefox Nightly 50.x

### ISSUE THREAD

**Issue by rahilwazir** [wspl/mactype-hack#11]
Enabling the `gfx.direct2d.disabled` doesn't work on Firefox Nightly 50.x

And it works on Firefox Stable 47.x

**Comment by wspl** [comment]
Nightly is unstable and I even cannot open up the "Advanced" tab on "Option" page.

**Comment by rahilwazir** [comment]
I'm not sure, but Nightly settings working fine for me. :smile: You can atleast navigate to `about:config` and try?

**Comment by kud** [comment]
It doesn't work anymore with 51.x. :/
