### ISSUE TITLE
SimpleNote

### ISSUE THREAD

**Issue by Lenic** [wspl/mactype-hack#3]
Hi 你好:
    帮忙看下 [SimpleNote](http://simplenote.com/) 程序如何使用 MacType，好吗？谢谢了！

**Comment by wspl** [comment]
我粗略地看了下，这个程序也是 Electron 封装的…方法是用 ASAR 工具解包，然后在 `web-preferences` 里加上 `direct-write: false`，原理和 Atom 类似。你可以先自己试试…我抽空可能会写个专门针对 Electron 应用的 `web-preferences` 编辑工具。

**Comment by wspl** [comment]
@Lenic 最近才发现 Electron 程序都可以直接通过添加 `--disable-direct-write` 启动参数来直接禁用 Direct-Write 以使用 MacType，现已更新至 VSCode 的兼容方法中：[VSCode.md](https://github.com/wspl/mactype-hack/blob/master/vscode.md)，这个软件应该是通用的。

**Comment by Lenic** [comment]
@wspl 谢谢，已通过这种方式启动。
