### ISSUE TITLE
14295 Support

### ISSUE THREAD

**Issue by malimM** [wspl/mactype-hack#4]
Is 14295 supported? I updated to 14295 with MacType and kept on getting "Crtical_Process_Died". I tried installing after updating to 14295 and explorer.exe kept on crashing.
EDIT. I translated the ReadMe, thank you for your help. Which is the latest version of MacType?
Here's my [INI](https://github.com/malimM/MacType.and.modifiedProfile/blob/master/Decency.modified.English.ini)

**Comment by wspl** [comment]
[Here](https://mega.nz/#!l513gDIL) is my version of MacType. You can override your MacType via Windows PE. Just try it.

**Comment by malimM** [comment]
@wspl What's the Decryption key?

**Comment by wspl** [comment]
@malimM Is the link invalid or the zip file is encrypted?...Forget it, I was upload it to github:
[MacType.zip](https://github.com/wspl/mactype-hack/files/205977/MacType.zip)
