### ISSUE TITLE
PowerShell support?

### ISSUE THREAD

**Issue by wowse** [wspl/mactype-hack#5]
With all these various hacks you've made to make incompatible apps to work with MacType, I was thinking that it could be possible to make PowerShell hack. I know that PS is kinda customizable as people had written various hacks such as aero glass support and others.
What do you think?

**Comment by wspl** [comment]
About PowerShell, to be honest, it uses the old font rendering mechanism same as cmd. So it has little possibility to compatible with MacType.
However, you can try [cmder](http://cmder.net/). It is a beautiful&elegent shell for terminal program (e.g. cmd, ps, git bash). And it support MacType.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/2133311/14448755/31a36800-009e-11e6-8a06-9325ca34026c.png)

**Comment by wowse** [comment]
I tried Cmder and it's pretty nice, but I still would rather use PowerShell. If it isn't that hard, please try making PowerShell fix.
