### ISSUE TITLE
MacType theme configuration?

### ISSUE THREAD

**Issue by rahilwazir** [wspl/mactype-hack#9]
Where can I find MacType theme configuration for [JetBrains](https://github.com/wspl/mactype-hack/blob/master/jetbrains.md)? I see only MacType profile settings and if so how do I suppose to add there?

**Comment by wspl** [comment]
The theme configuration is directed by this menu item:
![image](https://cloud.githubusercontent.com/assets/2133311/16571400/ed06a28e-428d-11e6-8e54-9b879c50f8e1.png)
